app/models.py
from werkzeug.security import generate_password_hash, check_password_hash
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from flask import current_app
from flask.ext.login import UserMixin
from . import login_manager, db


class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(64), unique=True, nullable=False, index=True)
    username = db.Column(db.String(64), unique=True, index=True)
    password_hash = db.Column(db.String(128))
    confirmed = db.Column(db.Boolean, default=False)
    bookmarks = db.relationship('BookMarks', backref='user', lazy='dynamic')

    @property
    def password(self):
        raise AttributeError("password is not readable can only write")

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    def generate_confirmation_token(self, expiration=3600):
        s = Serializer(current_app.config['SECRET_KEY'], expiration)
        return s.dumps({'confirm': self.id})

    def confirm(self, token):
        s = Serializer(current_app.config['SECRET_KEY'])
        try:
            data = s.loads(token)
        except:
            return False

        if data.get('confirm') != self.id:
            return False
        self.confirmed = True
        db.session.add(self)
        return True

    def __repr__(self):
        return '<User %r>' % self.username


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class BookMarks(UserMixin, db.Model):
    __tablename__ = 'bookmarks'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    url = db.Column(db.String(256), nullable=False)
    image_url = db.Column(db.String(256), unique=True)
    description = db.Column(db.String(128))
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))

    def __repr__(self):
        return '%r' % self.url

app/main/forms.py
from flask.ext.wtf import Form
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import Required, URL, Length


class Bookmarks(Form):
    bookmark_url = StringField('Bookmark URL', validators=[Required(), Length(1, 256), URL()])
    comment = TextAreaField('About the URL', validators=[Required(), Length(1, 64)])
    submit = SubmitField('Add Bookmark')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask.ext.mail import Mail
from flask_sqlalchemy import SQLAlchemy
from flask.ext.login import LoginManager
from config import config


bootstrap = Bootstrap()
mail = Mail()
db = SQLAlchemy()

login_manager = LoginManager()
login_manager.login_view = 'auth.login'
login_manager.session_protection = 'strong'


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    bootstrap.init_app(app)
    mail.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/auth')
    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

app/main/views.py
from flask import redirect, url_for, render_template, flash
from flask.ext.login import login_required, current_user
from . import main
from app import db
from .forms import Bookmarks
from ..models import BookMarks
import os
basedir = os.path.abspath(os.path.dirname(__file__))


@main.route('/')
def index():
    return redirect(url_for('auth.login'))


@main.route('/bookmarks')
@login_required
def bookmarks():
    bookmark_urls = current_user.bookmarks.all()
    return render_template('index.html', bookmarks=bookmark_urls)


@main.route('/addbookmarks', methods=['GET', 'POST'])
@login_required
def add_bookmarks():
    from extensions import fetch_image
    '''
    This function adds the bookmarks to the database, and it will also check whether the url being added
    is already in users list of urls
    current_user._get_current_object() is used to get the 'current_user' object
    :return:
    '''
    form = Bookmarks()
    if form.validate_on_submit():
        url = form.bookmark_url.data
        active_user = current_user._get_current_object()
        for bookmark in active_user.bookmarks.all():
            if bookmark.url == url:
                flash('The URL u are about to add already exists')
                return redirect(url_for('main.bookmarks'))
        bookmark_object = BookMarks()
        bookmark_object.description = form.comment.data
        bookmark_object.url = url
        bookmark_object.user = active_user
        fetch_image.delay(bookmark_object, url, active_user)
        flash('Your added bookmark is being processed and uploaded')
        db.session.commit()
        return redirect(url_for('main.bookmarks'))
    return render_template('add_bookmarks.html', form=form)

app/templates/add_bookmarks.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Bookmarks - Add bookmarks{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Add Bookmark</h1>
</div>
<div class="col-md-8">
    {{ wtf.quick_form(form) }}
    <br>
</div>
{% endblock %}

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}Bookmarks{% endblock %}


{% block head %}
{{ super() }}
<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('main.bookmarks') }}">Bookmarks</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                <li><a href="{{ url_for('auth.logout') }}">Log Out</a></li>
                <li><a href="{{ url_for('main.add_bookmarks') }}">Click here to add bookmarks</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}

    {% block page_content %}{% endblock %}
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
{% endblock %}

app/templates/error.html
{% extends "base.html" %}

{% block title %}Bookmarks{% endblock %}


{% block page_content %}


<div class="page-header">
    Something went wrong, r u sure u gave the correct url?
</div>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block title %}Bookmarks{% endblock %}

{% macro icon(site, title="") %}
    <div class="thumbnail">
        <img src="{{ site }}" alt="{{ title }}" style="width: 350px;">
    </div>
{% endmacro %}

{% block page_content %}


<div class="page-header">
    <h3>Hello, {% if current_user.is_authenticated %}{{ current_user.username }}! {% endif %} your bookmarks are</h3>
</div>
<div class="row">
    {% for bookmark in bookmarks %}
        {% if bookmark.image_url %}
            <div class="col-md-4">
                <a href="{{ bookmark. url }}" target="_blank" class="thumbnail">
                    {{ icon(bookmark.image_url) }}
                    <p>{{  bookmark.description }}</p>
                </a>
            </div>
        {% endif %}
    {% endfor %}
</div>
{% endblock %}